import {
  Project,
  User,
  Review,
  DirectMessage,
  HeatmapDay,
  Friendship,
  ChatRoom,
  GroupChatMessage,
  AppNotification,
} from '../types';

const STORAGE_KEYS = {
  USER: 'wedidthis_user',
  ALL_USERS: 'wedidthis_all_users',
  FOLLOWING: 'wedidthis_following',
  PROJECTS: 'wedidthis_projects',
  REVIEWS: 'wedidthis_reviews',
  MESSAGES: 'wedidthis_messages',
  FRIENDSHIPS: 'wedidthis_friendships',
  CHAT_ROOMS: 'wedidthis_chat_rooms',
  GROUP_MESSAGES: 'wedidthis_group_messages',
  LIKED_PROJECTS: 'wedidthis_liked_projects',
  NOTIFICATIONS: 'wedidthis_notifications',
  LOGIN_DATES: 'lockedin_login_dates',
  CLEARED_ACCOUNTS_FLAG: 'wedidthis_strict_zero_fabricated_rule_v4',
};

// Immediate purge of any legacy fake seed accounts, fabricated notifications, and dummy builds
if (typeof window !== 'undefined') {
  try {
    if (!localStorage.getItem(STORAGE_KEYS.CLEARED_ACCOUNTS_FLAG)) {
      // Purge all fabricated notifications: zero notifications by default
      localStorage.removeItem(STORAGE_KEYS.NOTIFICATIONS);

      // Clean existing projects to remove any fake seed builds
      const rawProjects = localStorage.getItem(STORAGE_KEYS.PROJECTS);
      if (rawProjects) {
        const projs: Project[] = JSON.parse(rawProjects);
        // Keep only projects authored by the actual currentUser
        const rawUser = localStorage.getItem(STORAGE_KEYS.USER);
        const currentUser: User | null = rawUser ? JSON.parse(rawUser) : null;
        if (currentUser) {
          const realProjects = projs.filter((p) => p.authorId === currentUser.id);
          localStorage.setItem(STORAGE_KEYS.PROJECTS, JSON.stringify(realProjects));
        } else {
          localStorage.removeItem(STORAGE_KEYS.PROJECTS);
        }
      }

      // Clean users to enforce 1 account per email and delete any fake seed users
      const rawUsers = localStorage.getItem(STORAGE_KEYS.ALL_USERS);
      if (rawUsers) {
        const users: User[] = JSON.parse(rawUsers);
        const seenEmails = new Set<string>();
        const realUsers: User[] = [];
        for (const u of users) {
          const email = (u.email || '').trim().toLowerCase();
          // Filter out dummy/seed domains
          if (email && !email.endsWith('@wedidthis.dev')) {
            if (!seenEmails.has(email)) {
              seenEmails.add(email);
              realUsers.push(u);
            }
          }
        }
        localStorage.setItem(STORAGE_KEYS.ALL_USERS, JSON.stringify(realUsers));
      }

      // Sanitize any existing email matching eileen.a.rehman@gmail.com
      const rawUser = localStorage.getItem(STORAGE_KEYS.USER);
      if (rawUser && rawUser.includes('eileen.a.rehman@gmail.com')) {
        localStorage.setItem(STORAGE_KEYS.USER, rawUser.replaceAll('eileen.a.rehman@gmail.com', 'xxx@gmail.com'));
      }
      const rawAllUsers = localStorage.getItem(STORAGE_KEYS.ALL_USERS);
      if (rawAllUsers && rawAllUsers.includes('eileen.a.rehman@gmail.com')) {
        localStorage.setItem(STORAGE_KEYS.ALL_USERS, rawAllUsers.replaceAll('eileen.a.rehman@gmail.com', 'xxx@gmail.com'));
      }

      localStorage.setItem(STORAGE_KEYS.CLEARED_ACCOUNTS_FLAG, 'true');
    }
  } catch (e) {
    console.error('Storage cleanup failed', e);
  }
}

// Clean storage helper functions with strict 1 account per email guarantee
export const storage = {
  getUser: (): User | null => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.USER);
      return data ? JSON.parse(data) : null;
    } catch {
      return null;
    }
  },
  setUser: (user: User | null) => {
    if (user) {
      localStorage.setItem(STORAGE_KEYS.USER, JSON.stringify(user));
      storage.registerUser(user);
    } else {
      localStorage.removeItem(STORAGE_KEYS.USER);
    }
  },
  getAllUsers: (): User[] => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.ALL_USERS);
      const users: User[] = data ? JSON.parse(data) : [];
      // Clean and filter out fake dummy accounts (e.g. from the old friending bug)
      const validUsers: User[] = [];
      const seenEmails = new Set<string>();
      const seenHandles = new Set<string>();
      const seenIds = new Set<string>();

      for (const u of users) {
        if (!u || !u.id || !u.email) continue;
        // Purge dummy accounts generated by the old bug
        if (u.bio === 'Teen builder on We Did This' || u.email.endsWith('@wedidthis.dev')) {
          continue;
        }
        const normEmail = (u.email || '').trim().toLowerCase();
        const normHandle = (u.handle || '').replace(/^@/, '').trim().toLowerCase();
        if (normEmail && !seenEmails.has(normEmail) && !seenIds.has(u.id)) {
          seenEmails.add(normEmail);
          if (normHandle) seenHandles.add(normHandle);
          seenIds.add(u.id);
          validUsers.push(u);
        }
      }

      // Ensure currentUser is included if signed in
      const rawUser = localStorage.getItem(STORAGE_KEYS.USER);
      if (rawUser) {
        try {
          const currentUser: User = JSON.parse(rawUser);
          if (currentUser && currentUser.id && currentUser.email) {
            const normEmail = currentUser.email.trim().toLowerCase();
            if (!seenEmails.has(normEmail) && !seenIds.has(currentUser.id)) {
              validUsers.push(currentUser);
            }
          }
        } catch {
          // ignore
        }
      }

      return validUsers;
    } catch {
      return [];
    }
  },
  saveAllUsers: (users: User[]) => {
    // Strictly deduplicate by email address (1 account per email)
    const seenEmails = new Set<string>();
    const deduplicated: User[] = [];
    for (const u of users) {
      if (!u || !u.email) continue;
      const norm = u.email.trim().toLowerCase();
      if (norm && !seenEmails.has(norm)) {
        seenEmails.add(norm);
        deduplicated.push(u);
      }
    }
    localStorage.setItem(STORAGE_KEYS.ALL_USERS, JSON.stringify(deduplicated));
  },
  getUserByEmail: (email: string): User | null => {
    try {
      const users = storage.getAllUsers();
      const clean = email.trim().toLowerCase();
      return users.find((u) => (u.email || '').trim().toLowerCase() === clean) || null;
    } catch {
      return null;
    }
  },
  getUserByHandle: (handle: string): User | null => {
    try {
      const users = storage.getAllUsers();
      const clean = handle.replace(/^@/, '').trim().toLowerCase();
      return users.find((u) => (u.handle || '').replace(/^@/, '').trim().toLowerCase() === clean) || null;
    } catch {
      return null;
    }
  },
  getUserById: (id: string): User | null => {
    try {
      const users = storage.getAllUsers();
      return users.find((u) => u.id === id) || null;
    } catch {
      return null;
    }
  },
  registerUser: (user: User) => {
    if (!user || !user.id || !user.email) return;
    try {
      const existingUsers = storage.getAllUsers();
      const normalizedEmail = (user.email || '').trim().toLowerCase();
      const normalizedHandle = (user.handle || '').replace(/^@/, '').trim().toLowerCase();

      const filtered = existingUsers.filter((u) => {
        const uEmail = (u.email || '').trim().toLowerCase();
        const uHandle = (u.handle || '').replace(/^@/, '').trim().toLowerCase();
        return u.id !== user.id && uEmail !== normalizedEmail && uHandle !== normalizedHandle;
      });
      const updated = [user, ...filtered];
      localStorage.setItem(STORAGE_KEYS.ALL_USERS, JSON.stringify(updated));
    } catch (e) {
      console.error('Failed to register user globally', e);
    }
  },
  isEmailRegistered: (email: string): boolean => {
    return Boolean(storage.getUserByEmail(email));
  },
  deleteAllAccounts: () => {
    try {
      localStorage.removeItem(STORAGE_KEYS.USER);
      localStorage.removeItem(STORAGE_KEYS.ALL_USERS);
      localStorage.removeItem(STORAGE_KEYS.FOLLOWING);
    } catch {
      // ignore
    }
  },
  getFollowing: (): string[] => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.FOLLOWING);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },
  saveFollowing: (ids: string[]) => {
    localStorage.setItem(STORAGE_KEYS.FOLLOWING, JSON.stringify(ids));
  },
  getProjects: (): Project[] => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.PROJECTS);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },
  saveProjects: (projects: Project[]) => {
    localStorage.setItem(STORAGE_KEYS.PROJECTS, JSON.stringify(projects));
  },
  getReviews: (): Review[] => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.REVIEWS);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },
  saveReviews: (reviews: Review[]) => {
    localStorage.setItem(STORAGE_KEYS.REVIEWS, JSON.stringify(reviews));
  },
  getMessages: (): DirectMessage[] => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.MESSAGES);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },
  saveMessages: (messages: DirectMessage[]) => {
    localStorage.setItem(STORAGE_KEYS.MESSAGES, JSON.stringify(messages));
  },
  getFriendships: (): Record<string, Friendship> => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.FRIENDSHIPS);
      if (!data) return {};
      const parsed = JSON.parse(data);
      const cleaned: Record<string, Friendship> = {};
      const allUsers = storage.getAllUsers();
      const userMap = new Map<string, User>(allUsers.map((u) => [u.id, u]));

      for (const [key, fr] of Object.entries(parsed as Record<string, Friendship>)) {
        if (!fr || !fr.userId || !fr.friendId) continue;
        // Verify friend is not a dummy user created by the old bug
        if (
          fr.friend?.bio === 'Teen builder on We Did This' ||
          fr.friend?.email?.endsWith('@wedidthis.dev')
        ) {
          continue;
        }
        // Match real users if available
        const realFriend = userMap.get(fr.friendId) || fr.friend;
        const realSender = userMap.get(fr.userId) || fr.sender;
        if (realFriend) {
          cleaned[fr.id || key] = {
            ...fr,
            id: fr.id || key,
            friend: realFriend,
            sender: realSender,
          };
        }
      }
      return cleaned;
    } catch {
      return {};
    }
  },
  saveFriendships: (friendships: Record<string, Friendship>) => {
    localStorage.setItem(STORAGE_KEYS.FRIENDSHIPS, JSON.stringify(friendships));
  },
  getChatRooms: (): ChatRoom[] => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.CHAT_ROOMS);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },
  saveChatRooms: (rooms: ChatRoom[]) => {
    localStorage.setItem(STORAGE_KEYS.CHAT_ROOMS, JSON.stringify(rooms));
  },
  getGroupMessages: (): Record<string, GroupChatMessage[]> => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.GROUP_MESSAGES);
      return data ? JSON.parse(data) : {};
    } catch {
      return {};
    }
  },
  saveGroupMessages: (groupMessages: Record<string, GroupChatMessage[]>) => {
    localStorage.setItem(STORAGE_KEYS.GROUP_MESSAGES, JSON.stringify(groupMessages));
  },
  getLikedProjectIds: (): string[] => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.LIKED_PROJECTS);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },
  saveLikedProjectIds: (ids: string[]) => {
    localStorage.setItem(STORAGE_KEYS.LIKED_PROJECTS, JSON.stringify(ids));
  },
  getNotifications: (): AppNotification[] => {
    try {
      const data = localStorage.getItem(STORAGE_KEYS.NOTIFICATIONS);
      if (data) {
        const parsed: AppNotification[] = JSON.parse(data);
        // Strictly return only real account notifications (filter out any legacy fake ones)
        return parsed.filter(
          (n) =>
            !n.id.startsWith('notif_init_') &&
            !n.id.startsWith('fake_') &&
            !n.message.includes('@elena_cad')
        );
      }
      return [];
    } catch {
      return [];
    }
  },
  saveNotifications: (notifications: AppNotification[]) => {
    try {
      localStorage.setItem(STORAGE_KEYS.NOTIFICATIONS, JSON.stringify(notifications));
    } catch {
      // ignore
    }
  },
  getLoginDates: (userId: string): string[] => {
    try {
      const data = localStorage.getItem(`${STORAGE_KEYS.LOGIN_DATES}_${userId}`);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  },
  recordDailyLogin: (userId: string): { loginDates: string[]; isNewDayLogin: boolean } => {
    try {
      const existing = storage.getLoginDates(userId);
      const todayStr = new Date().toISOString().split('T')[0];
      const isNewDayLogin = !existing.includes(todayStr);
      if (isNewDayLogin) {
        const updated = [todayStr, ...existing.filter((d) => d !== todayStr)];
        localStorage.setItem(`${STORAGE_KEYS.LOGIN_DATES}_${userId}`, JSON.stringify(updated));
        return { loginDates: updated, isNewDayLogin: true };
      }
      return { loginDates: existing, isNewDayLogin: false };
    } catch {
      return { loginDates: [], isNewDayLogin: false };
    }
  },
  clearAll: () => {
    localStorage.clear();
  },
};

// Generates dynamic activity heatmap based on real user actions including daily logins
export function generateUserHeatmapData(
  activityCount: number = 0,
  userProjects: Project[] = [],
  userReviews: Review[] = [],
  userLoginDates: string[] = []
): HeatmapDay[] {
  const days: HeatmapDay[] = [];
  const now = new Date();

  // Map real activities to dates
  const dateCounts: Record<string, number> = {};
  userLoginDates.forEach((d) => {
    dateCounts[d] = (dateCounts[d] || 0) + 1;
  });
  userProjects.forEach((p) => {
    if (p.createdAt) {
      const key = p.createdAt.split('T')[0];
      dateCounts[key] = (dateCounts[key] || 0) + 1;
    }
  });
  userReviews.forEach((r) => {
    if (r.createdAt) {
      const key = r.createdAt.split('T')[0];
      dateCounts[key] = (dateCounts[key] || 0) + 1;
    }
  });

  for (let i = 83; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    const dateStr = d.toISOString().split('T')[0];
    const isToday = i === 0;
    const realCount = dateCounts[dateStr] || (isToday ? activityCount : 0);
    const level = realCount > 3 ? 4 : realCount > 2 ? 3 : realCount > 1 ? 2 : realCount > 0 ? 1 : 0;
    days.push({
      date: dateStr,
      count: realCount,
      level: level as 0 | 1 | 2 | 3 | 4,
    });
  }
  return days;
}
